In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('ai_job_replacement_2020_2026.csv')

In [5]:
df.head()

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level
0,0,Data Analyst,Technology,Canada,2021,26.22,30.94,73.20,101839.02,99454.42,-2.34,2.66,15.23,86.62,2
1,1,Accountant,Finance,Brazil,2020,52.08,56.41,2.06,146389.18,139516.59,-4.69,10.43,26.36,18.34,5
2,2,Teacher,Technology,USA,2020,31.30,31.61,43.19,64947.50,58369.41,-10.13,8.14,36.29,36.64,2
3,3,Customer Support Rep,Technology,Brazil,2021,56.92,63.42,19.97,91708.13,86715.70,-5.44,6.11,64.68,17.05,5
4,4,Teacher,Manufacturing,Japan,2024,14.55,17.17,96.56,127007.68,119379.11,-6.01,2.08,71.58,44.02,3

In [6]:
df['industry'].nunique()

8

In [26]:
pd.get_dummies(df,columns=['ai_adoption_level'])

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,...,ai_adoption_level_99.84,ai_adoption_level_99.85,ai_adoption_level_99.86,ai_adoption_level_99.88,ai_adoption_level_99.9,ai_adoption_level_99.94,ai_adoption_level_99.95,ai_adoption_level_99.96,ai_adoption_level_99.97,ai_adoption_level_99.98
0,0,Data Analyst,Technology,Canada,2021,26.22,30.94,73.20,101839.02,99454.42,...,False,False,False,False,False,False,False,False,False,False
1,1,Accountant,Finance,Brazil,2020,52.08,56.41,2.06,146389.18,139516.59,...,False,False,False,False,False,False,False,False,False,False
2,2,Teacher,Technology,USA,2020,31.30,31.61,43.19,64947.50,58369.41,...,False,False,False,False,False,False,False,False,False,False
3,3,Customer Support Rep,Technology,Brazil,2021,56.92,63.42,19.97,91708.13,86715.70,...,False,False,False,False,False,False,False,False,False,False
4,4,Teacher,Manufacturing,Japan,2024,14.55,17.17,96.56,127007.68,119379.11,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14995,HR Manager,Finance,Canada,2025,44.05,38.61,1.06,74458.30,76568.31,...,False,False,False,False,False,False,False,False,False,False
14996,14996,Software Engineer,Energy,India,2023,15.68,15.37,34.93,97728.22,94274.12,...,False,False,False,False,False,False,False,False,False,False
14997,14997,Truck Driver,Transportation,Japan,2026,80.16,67.09,48.57,74801.26,79989.74,...,False,False,False,False,False,False,False,False,False,False
14998,14998,Customer Support Rep,Transportation,USA,2020,34.54,37.05,49.30,124632.88,127378.53,...,False,False,False,False,False,False,False,False,False,False
14999,14999,Mechanical Engineer,Retail,Australia,2023,47.62,43.18,19.67,63637.98,66559.86,...,False,False,False,False,False,False,False,False,False,False

In [11]:
pd.get_dummies(df,columns=['job_id','job_role'],drop_first=True)

,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,...,job_id_14999,job_role_Customer Support Rep,job_role_Data Analyst,job_role_Financial Analyst,job_role_HR Manager,job_role_Marketing Specialist,job_role_Mechanical Engineer,job_role_Software Engineer,job_role_Teacher,job_role_Truck Driver
0,Technology,Canada,2021,26.22,30.94,73.20,101839.02,99454.42,-2.34,2.66,...,False,False,True,False,False,False,False,False,False,False
1,Finance,Brazil,2020,52.08,56.41,2.06,146389.18,139516.59,-4.69,10.43,...,False,False,False,False,False,False,False,False,False,False
2,Technology,USA,2020,31.30,31.61,43.19,64947.50,58369.41,-10.13,8.14,...,False,False,False,False,False,False,False,False,True,False
3,Technology,Brazil,2021,56.92,63.42,19.97,91708.13,86715.70,-5.44,6.11,...,False,True,False,False,False,False,False,False,False,False
4,Manufacturing,Japan,2024,14.55,17.17,96.56,127007.68,119379.11,-6.01,2.08,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,Finance,Canada,2025,44.05,38.61,1.06,74458.30,76568.31,2.83,-17.88,...,False,False,False,False,True,False,False,False,False,False
14996,Energy,India,2023,15.68,15.37,34.93,97728.22,94274.12,-3.53,18.14,...,False,False,False,False,False,False,False,True,False,False
14997,Transportation,Japan,2026,80.16,67.09,48.57,74801.26,79989.74,6.94,26.51,...,False,False,False,False,False,False,False,False,False,True
14998,Transportation,USA,2020,34.54,37.05,49.30,124632.88,127378.53,2.20,10.36,...,False,True,False,False,False,False,False,False,False,False
14999,Retail,Australia,2023,47.62,43.18,19.67,63637.98,66559.86,4.59,16.29,...,True,False,False,False,False,False,True,False,False,False

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:6],df.iloc[:,-1],test_size=0.2,random_state=2)
X_train.head()

,job_id,job_role,industry,country,year,automation_risk_percent
1154,1154,HR Manager,Energy,UK,2025,33.25
9804,9804,HR Manager,Energy,Australia,2023,74.84
7919,7919,Marketing Specialist,Energy,USA,2021,54.50
4854,4854,Financial Analyst,Education,Australia,2023,66.30
5947,5947,Customer Support Rep,Finance,USA,2025,74.29

In [14]:

from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
     

X_train_new = ohe.fit_transform(X_train[['country','year']])
     

X_test_new = ohe.transform(X_test[['country','year']])
X_train_new.shape

(12000, 14)

In [21]:
np.hstack((X_train[['country','year']].values,X_train_new))

array([['UK', 2025, 0, ..., 0, 1, 0],
       ['Australia', 2023, 0, ..., 0, 0, 0],
       ['USA', 2021, 0, ..., 0, 0, 0],
       ...,
       ['Singapore', 2020, 0, ..., 0, 0, 0],
       ['Singapore', 2021, 0, ..., 0, 0, 0],
       ['Japan', 2025, 0, ..., 0, 1, 0]], shape=(12000, 16), dtype=object)

In [24]:
counts = df['year'].value_counts()
df['year'].nunique()
threshold = 100
repl = counts[counts <= threshold].index
pd.get_dummies(df['year'].replace(repl, 'common')).sample(10)

        2020   2021   2022   2023   2024   2025   2026
10672  False  False   True  False  False  False  False
13425   True  False  False  False  False  False  False
6195   False  False  False  False  False  False   True
11724  False  False  False  False  False   True  False
329    False  False   True  False  False  False  False
12504  False  False  False   True  False  False  False
1144   False  False   True  False  False  False  False
2056   False  False  False  False  False   True  False
9063   False  False  False   True  False  False  False
13916   True  False  False  False  False  False  False